package primero;
// Generated 01-feb-2018 11:06:06 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

	private String codAsig;
	private String nombre;
	private Byte horasSemanales;
	private Short horasTotales;
	private Set horarios = new HashSet(0);
	private Set repartos = new HashSet(0);

	public Asignatura() {
	}

	public Asignatura(String codAsig, String nombre) {
		this.codAsig = codAsig;
		this.nombre = nombre;
	}

	public Asignatura(String codAsig, String nombre, Byte horasSemanales, Short horasTotales, Set horarios,
			Set repartos) {
		this.codAsig = codAsig;
		this.nombre = nombre;
		this.horasSemanales = horasSemanales;
		this.horasTotales = horasTotales;
		this.horarios = horarios;
		this.repartos = repartos;
	}

	public String getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(String codAsig) {
		this.codAsig = codAsig;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Byte getHorasSemanales() {
		return this.horasSemanales;
	}

	public void setHorasSemanales(Byte horasSemanales) {
		this.horasSemanales = horasSemanales;
	}

	public Short getHorasTotales() {
		return this.horasTotales;
	}

	public void setHorasTotales(Short horasTotales) {
		this.horasTotales = horasTotales;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

	public Set getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set repartos) {
		this.repartos = repartos;
	}

}
