package primero;
// Generated 01-feb-2018 11:06:06 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private CursoId id;
	private Ofertaeducativa ofertaeducativa;
	private Profesor profesor;
	private Set horarios = new HashSet(0);
	private Set repartos = new HashSet(0);

	public Curso() {
	}

	public Curso(CursoId id, Ofertaeducativa ofertaeducativa, Profesor profesor) {
		this.id = id;
		this.ofertaeducativa = ofertaeducativa;
		this.profesor = profesor;
	}

	public Curso(CursoId id, Ofertaeducativa ofertaeducativa, Profesor profesor, Set horarios, Set repartos) {
		this.id = id;
		this.ofertaeducativa = ofertaeducativa;
		this.profesor = profesor;
		this.horarios = horarios;
		this.repartos = repartos;
	}

	public CursoId getId() {
		return this.id;
	}

	public void setId(CursoId id) {
		this.id = id;
	}

	public Ofertaeducativa getOfertaeducativa() {
		return this.ofertaeducativa;
	}

	public void setOfertaeducativa(Ofertaeducativa ofertaeducativa) {
		this.ofertaeducativa = ofertaeducativa;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

	public Set getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set repartos) {
		this.repartos = repartos;
	}

}
