package primero;
// Generated 01-feb-2018 11:06:06 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String codProf;
	private String nombre;
	private String apellidos;
	private Date fechaAlta;
	private Set repartos = new HashSet(0);
	private Set cursos = new HashSet(0);

	public Profesor() {
	}

	public Profesor(String codProf, Date fechaAlta) {
		this.codProf = codProf;
		this.fechaAlta = fechaAlta;
	}

	public Profesor(String codProf, String nombre, String apellidos, Date fechaAlta, Set repartos, Set cursos) {
		this.codProf = codProf;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaAlta = fechaAlta;
		this.repartos = repartos;
		this.cursos = cursos;
	}

	public String getCodProf() {
		return this.codProf;
	}

	public void setCodProf(String codProf) {
		this.codProf = codProf;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Set getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set repartos) {
		this.repartos = repartos;
	}

	public Set getCursos() {
		return this.cursos;
	}

	public void setCursos(Set cursos) {
		this.cursos = cursos;
	}

}
