package hibernateUtils;
// Generated 01-feb-2018 12:24:01 by Hibernate Tools 5.2.8.Final

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

	private String codAsig;
	private String nombre;
	private Byte horasSemanales;
	private Short horasTotales;

	public Asignatura() {
	}

	public Asignatura(String codAsig, String nombre) {
		this.codAsig = codAsig;
		this.nombre = nombre;
	}

	public Asignatura(String codAsig, String nombre, Byte horasSemanales, Short horasTotales) {
		this.codAsig = codAsig;
		this.nombre = nombre;
		this.horasSemanales = horasSemanales;
		this.horasTotales = horasTotales;
	}

	public String getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(String codAsig) {
		this.codAsig = codAsig;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Byte getHorasSemanales() {
		return this.horasSemanales;
	}

	public void setHorasSemanales(Byte horasSemanales) {
		this.horasSemanales = horasSemanales;
	}

	public Short getHorasTotales() {
		return this.horasTotales;
	}

	public void setHorasTotales(Short horasTotales) {
		this.horasTotales = horasTotales;
	}

}
