package hibernateUtils;
// Generated 01-feb-2018 12:24:01 by Hibernate Tools 5.2.8.Final

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private CursoId id;
	private String codTutor;

	public Curso() {
	}

	public Curso(CursoId id, String codTutor) {
		this.id = id;
		this.codTutor = codTutor;
	}

	public CursoId getId() {
		return this.id;
	}

	public void setId(CursoId id) {
		this.id = id;
	}

	public String getCodTutor() {
		return this.codTutor;
	}

	public void setCodTutor(String codTutor) {
		this.codTutor = codTutor;
	}

}
