package hibernateUtils;
// Generated 01-feb-2018 12:24:01 by Hibernate Tools 5.2.8.Final

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

	private HorarioId id;

	public Horario() {
	}

	public Horario(HorarioId id) {
		this.id = id;
	}

	public HorarioId getId() {
		return this.id;
	}

	public void setId(HorarioId id) {
		this.id = id;
	}

}
