package hibernateUtils;
// Generated 01-feb-2018 12:24:01 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Ofertaeducativa generated by hbm2java
 */
public class Ofertaeducativa implements java.io.Serializable {

	private String codOe;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Date fechaLey;

	public Ofertaeducativa() {
	}

	public Ofertaeducativa(String codOe) {
		this.codOe = codOe;
	}

	public Ofertaeducativa(String codOe, String nombre, String descripcion, String tipo, Date fechaLey) {
		this.codOe = codOe;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.fechaLey = fechaLey;
	}

	public String getCodOe() {
		return this.codOe;
	}

	public void setCodOe(String codOe) {
		this.codOe = codOe;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getFechaLey() {
		return this.fechaLey;
	}

	public void setFechaLey(Date fechaLey) {
		this.fechaLey = fechaLey;
	}

}
