package hibernateUtils;
// Generated 01-feb-2018 12:24:01 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String codProf;
	private String nombre;
	private String apellidos;
	private Date fechaAlta;

	public Profesor() {
	}

	public Profesor(String codProf, Date fechaAlta) {
		this.codProf = codProf;
		this.fechaAlta = fechaAlta;
	}

	public Profesor(String codProf, String nombre, String apellidos, Date fechaAlta) {
		this.codProf = codProf;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaAlta = fechaAlta;
	}

	public String getCodProf() {
		return this.codProf;
	}

	public void setCodProf(String codProf) {
		this.codProf = codProf;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

}
