package hibernateUtils;
// Generated 01-feb-2018 12:24:01 by Hibernate Tools 5.2.8.Final

/**
 * Reparto generated by hbm2java
 */
public class Reparto implements java.io.Serializable {

	private RepartoId id;

	public Reparto() {
	}

	public Reparto(RepartoId id) {
		this.id = id;
	}

	public RepartoId getId() {
		return this.id;
	}

	public void setId(RepartoId id) {
		this.id = id;
	}

}
